package org.example.rulebased.streaming.flinkdroolsdynamic;

import org.example.rulebased.streaming.flinkdroolsdynamic.dto.FireAlarm;
import org.example.rulebased.streaming.flinkdroolsdynamic.dto.SensorData;


declare SensorData
    @role( event )
    @timestamp( date )
    @expires( 10s )
end

declare FireAlarm
    @role( event )
    @timestamp( alarmDate )
    @expires( 5s )
end

query FindSensorData
    $s: SensorData()
end

query FindAlarm(String sensorDataId)
    $f: FireAlarm(id == sensorDataId)
end
