package org.example.rulebased.streaming.flinkdroolsdynamic;

declare SensorData
    @role( event )
    @timestamp( date )
    @expires( 10s )
end

declare FireAlarm
    @role( event )
    @timestamp( alarmDate )
    @expires( 5s )
end


rule "fire detect"
    when
        $s: SensorData(temperature > 50)
    then
        FireAlarm alarm = new FireAlarm($s.getId(), $s.getDate(), $s.getTemperature());
        insert(alarm);
end

query FindSensorData
    $s: SensorData()
end

query FindAlarm(String sensorDataId)
    $f: FireAlarm(id == sensorDataId)
end
